/**
 * The mark, as files a browser asks for by name: the same nested squares
 * the header draws — a green square with rounded corners, a dark one inset,
 * green at the centre — as a real favicon.ico (a PNG inside), an SVG, the
 * touch icon iOS wants for a bookmark or the home screen, the two sizes
 * Android's manifest wants. Rasterised once (no image library in the
 * build) and kept here as bytes; a data: URI in the head was not enough
 * for Safari on iOS, which showed nothing (2026-09-17).
 */
const B64 = {
  ico: "AAABAAEAICAAAAEAIACGAAAAFgAAAIlQTkcNChoKAAAADUlIRFIAAAAgAAAAIAgGAAAAc3p69AAAAE1JREFUeNpjYMAC5p3L+k8LzEAsGHXAyHIArSwj2lGjDhgSDuDhEyALjzpg+DqAUnWjDhh1wNB3wGg5MPIcMNoeGN4OGO0XjDpgoB0AAJlfLdQDPBbyAAAAAElFTkSuQmCC",
  png32: "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAATUlEQVR42mNgwALmncv6TwvMQCwYdcDIcgCtLCPaUaMOGBIO4OETIAuPOmD4OoBSdaMOGHXA0HfAaDkw8hww2h4Y3g4Y7ReMOmCgHQAAmV8t1AM8FvIAAAAASUVORK5CYII=",
  touch: "iVBORw0KGgoAAAANSUhEUgAAALQAAAC0CAYAAAA9zQYyAAACOUlEQVR42u3d0QmEMBBF0SkgSOq0KEuypYS0IGHQ8QRuAeM7+70Rye+6z6H/FNWfkYEGWkADLaCBFtBAC2gBDbSABlpAAy2ggRbQAhpoAQ20gAZaQAMtoAU00AIaaAENtIAGWkALaKAFNNACGmgBDTTQQAtooAU0YKr3A/IRBLQEtAS0BLSAloCWgJaAloAW0BLQEtAS0BLQAloCWgJaAloCWkBLQEtA76kdXQ8CGmiggQYaaKCBBhpoAQ000EADDTTQQAMNNNBAAy2ggQYaaKCBBhpooIEGGmigBTTQQAMNNNBAAw000EADDbSABhpooIEGGuh3g3Yf0AZ3H9AGBxpooIEGGmiggXYf0AZ3H9AGBxpooIEGGmiggXYf0AZ3H9AGBxpooIEGGmiggXYf0AZ3H9AGBxpooIEGGmiggXYf0AZ3H9AGBxpooIEGGmigDe4+oA3uPqCBBhpooIEGGmigDe4+oA3uPqCBBhpooIEG2l9SAA000EADDTTQQAMNtIAGGmiggQYaaKCBBhpooIEW0EADDTTQQAMNNNBAwwk00AIaaKCBBhpooIEGGmgBDTTQQAMNNNBAAw20BLSAloCWgJaAloAW0BLQEtAS0BLQAloCWgJaAloCWkBLQEtAS0BLQAto6ROgs5+PDlipZ2SggRbQQAtooAU00AJaQAMtoIEW0EALaKAFtIAGWkADLaCBFtBAC2gBDbSABlpAAy2ggRbQAhpoAQ20gAZaQAMNNNACGmgBvd4E+RaennsGO0UAAAAASUVORK5CYII=",
  icon192: "iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABS3GwHAAACeUlEQVR42u3TwQnAIBBFwS0gBOtMUZaUlvTk3YOosCO8Ajb5E3Ho1f9r0iiyPT9dAEgASAAIAAAEAAACAAABAIAAAEAAACAAABAAAAgAAAQAAAIAAAEAgAAAQAAAIAAAEAAACAAABAAAAgAAAQCAAABAAAAgAAAQAAAIAACUGICPr9TwfAQBIAEgASABIAEgASABIAEgASABIAEgASABIAEgASABIAEgASABIAEgASABIAGwpectWhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADcDMC9AADgXgAAcC8AALgXAINwLwAG4V4ADMK9ABiEewEwCPcCYBDuBcAg3AuAQbgXAINwLwAG4V4ADMK9ABiEewEwCPcCYBDuBcAg3AuAQbgXAINwLwAG4V4ADMK9ABiEewEwCPcCYBDuBcAgAADAIAAAwCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAgAAAQAAAIAAAEAAACAAABAAAAgAAAQCAAABAAAAgAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASABIAEgASABIAEgASABIAEgASABIAEgASABIAEgASABIAEgASABIAEgASABIAEjzAE49H19XDBEAAQCAAABAAAAgAAAQAAAIAAAEAAACAAABAIAAAEAAACAAABAAAAgAAAQAAAIAAAEAgAAAQAAAIAAAEAAACAAABAAAAsBPFwASABIAAgAAAbD7dRH1cgeYxuqKAAAAAElFTkSuQmCC",
  icon512: "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAALr0lEQVR42u3WwQlEIRBEQQMQMU6DMiRT0gy8DOgcqqES+LizrxQLba6xAXjPP5AJAAABYCYAAASAmQAAEABmAgBAAJgJAAABYCYAAASAmQAAEABmAgBAAJgJAAABYAIAAAFgAgAAAWACAAABYAIAAAFgAgAAAWACAAABYAIAAAFgAgAAAWACAEAAmAkAAAFgJgAABICZAAAQAGYCAEAAmAkAAAFgJgAABICZAAAQAGYCAEAAmAAAQACYAABAAJgAAEAAmAAAQACYAABAAJgAAEAAmAAAQACYAABAAJgAABAAZgIAQACYCQAAAWAmAAAEgJkAABAAZgIAQACYCQAAAWAmAAAEgJkAABAAJgAAEAAmAAAQACYAABAAJgAAEAAmAAAQACYAABAAJgAAEAAmAAAQACYAAASAmQAAEABmAgBAAJgJAAABYCYAAASAmQAAEABmAgBAAJgJAAABYCYAAASACQA/QgABYAIAAAFgAgAAAWACAAABYAIAAAFgAgAAAWACAAABYAIAAAFgAgBAAJgJAAABYCYAAASAmQAAEABmAgBAAJgJAAABYCYAAASAmQAAEABmAgBAAJgJAAABYAIAAAHgDwwASBtQPgIACAAAQAAAAAIAABAAAIAAAAAEAAAgAAAAAQAACAAAQAAAAAIAABAAAIAAAAAEAAAgAAAAAQAACAAAEAAAgAAAAAQAACAAAAABAAAIAABAAAAAAgAAEAAAgAAAAAQAACAAAAABAAAIAABAAAAAAgAAEAAAIAAAAAEAAAgAAEAAAAACAAAQAACAAAAABAAAIAAAAAEAAAgAAEAAAAACAAAQAACAAAAABAAAIAAAQAAAAAIAABAAAIAAAAAEAAAgAAAAAQAACAAAQAAAAAIAABAAAIAAIKHaOvCJG4QAQACAAAABgAAAAQACAAEAAgAEAAIABAAIAAQACAAEAAgAEAAIABAAIAAQACAAQAAgAMARBgGAAEAAAAIAAYAAAAQAAgABAAgABAACABAACAAEACAAEAAIAEAAIAAQAIAAQAAgAAABgABAAIAAAAGAAAABAAIAAQACAAQAAgAEAAgABAAIAAQACAAQAAgAEAAgABAAIABAACAAQACAAEAAIAAAAYAAQAAAAgABgAAABAACAAEACAAEAAIAEAAIAAQAIAAQAAgAQAAgABAAgABAACAAQACAAEAAgAAAAYAAAAEAAgABAAIABAACAAQAAgAEAAgABAAIABAACAAQACAAEAAgAEAAIAAQAIAAQAAgAAABgABAAAACAAGAAAAEAAIAAQAIAAQAAgAQAAgABAAgABAACABAACAAEAAgAEAAIABAAIAAQACAAAABgAAAAQACAAEAAgABAAIABAACAAQACAAEAAgAEAAIABAAIAAQAAgAQAAgABAAgABAACAAAAGAAEAAOMB4f94fAgAH2AHG+/P+EAA4wA4w3p/3hwDAAXaA8f68PwQADrADjPfn/SEAcIAdYO/P+wMBgAPsAHt/3h8IABxgB9j78/5AAOAAO8Den/cHAgAH2AH2/rw/BICPgAPsAHt/3h8CABxgB9j78/4QAOAAO8Den/eHAAAH2AH2/rw/BAAOsAOM9+f9IQBwgB1gvD/vDwGAA+wA4/15fwgAHGAHGO/P+0MA4AA7wHh/3h8CAAfYAcb78/4QADjADjDen/eHAMABdoDx/rw/BAAOsAOM9+cNIABwgB1g78/7AwGAA+wAe3/eHwgAHGAH2Pvz/kAA4AA7wN6f9wcCAAfYAfb+vD8EADjADrD35/0hAMABdoC9P+8PAQAOsAPs/Xl/CABwgL0B78/7QwDgADvAeH/eHwIAB9gBxvvz/hAAOMAOMN6f94cAwAF2gPH+vD8EAA6wA4z35/0hAHCAHWC8P+8PAYAD7ADj/Xl/CAAcYAcY78/7QwDgADvA3p/3BwIAB9gB9v68PxAAOMAOsPfn/YEAwAF2gL0/7w8EAA6wA+z9eX8IAHCAHWDvz/tDAIAD7AB7f94fAgAcYAfY+/P+EADgADvA3p/3hwDAAXaA8f68PwQADrADjPfn/SEAcIAdYLw/7w8BgAPsAOP9eX8IABxgBxjvz/tDAOAAO8B4f94fAgAH2AHG+/P+EAA4wA4w3p/3hwDAAXaAvT/vDwQADrAD7P15fyAAcIAdYO/P+wMBgAPsAHt/3h8IABxgB9j78/4QAOAAO8Den/eHAAAH2AH2/rw/BAA4wA6w9+f9IQDAAXaAvT/vDwGAA+wA4/15fwgAHGAHGO/P+0MA4AA7wHh/3h8CAAfYAcb78/4QADjADjDen/eHAMABdoDx/rw/BAAOsAOM9+f9IQBwgB1gvD/vDwGAA+wAe3/eHwgAHGAH2Pvz/kAA4AA7wN6f9wcCAAfYAfb+vD8QADjADrD35/0hAMABdoC9P+8PAQAOsAPs/Xl/CABwgB1g78/7QwCAA+wAe3/eHwIAB9gBxvvz/hAAOMAOMN6f94cAwAF2gPH+vD8EAA6wA4z35/0hAHCAHWC8P+8PAYAD7ADj/Xl/CAAcYAcY78/7QwDgADvAeH/eHwIAB9gB9v68PxAAOMAOsPfn/YEAwAF2gL0/7w8EAA6wA+z9eX8gAHCAHWDvz/tDAPgIOMAgABAAIABAACAAQACAAEAAgAAAAYAAQAA4wiAAEAAIAEAAIAAQAIAAQAAgAAABgABAAAACAAGAAAAEAAIAAQAIAAQAAgAQAAgABADgBiEAEAAgAEAAIABAAIAAQACAAAABgAAAAQACAAEAAgABAAIABAACAAQACAAEAAgAEAAIAHCEQQAgABAAgABAACAAAAGAAEAAAAIAAYAAAAQAAgABAAgABAACABAACAAEACAAEAAIAEAAIAAQACAAQAAgAEAAgABAAIAAAAGAAAABAAIAAQACAAEAAgAEAAIABAAIAAQACAAQAAgAEAAgABAACABAACAAEACAAEAAIAAAAYAAQAAAAgABgAAABAACAAEACAAEAAIAEAAIAAQAIAAQAAgAEAAgABAAIABAACAAQACAAEAAgAAAAYAAAAGAAAABAAIAAQACAAQAAgAEAAgABAAIABAACAAEACAAEAAIAEAAIAAQAIAAQAAgAAABgABAAAACAAGAAAAEAAIAAQAIAAQAAgAQAAgAAEAAAAACAAAQAACAAAAAAQAACAAAQAAAAAIAABAAAIAAAAAEAAAgAAAAAQAACAAAQAAAAAIAABAAAIAAAAAEAAAgAAAAAQAAAsBHAAABAAAIAABAAAAAAgAAEAAAgAAAAAQAACAAAAABAAAIAABAAAAAAgAAEAAAgAAAAAQAACAAAAABAAACAAAQAACAAAAABAAAIAAAAAEAAAgAAEAAAAACAAAQAACAAAAABAAAIAAAAAEAAAgAAEAAAAACAAAEAAAgAAAAAQAACAAAQAAAAAIAABAAAECuALDYPCIAf2AmAAAQACYAABAAJgAAEAAmAAAQACYAABAAJgAAEAAmAAAQACYAAASAmQAAEABmAgBAAJgJAAABYCYAAASAmQAAEABmAgBAAJgJAAABYCYAAASAmQAAEAAmAAAQACYAABAAJgAAEAAmAAAQACYAABAAJgAAEAAmAAAQACYAABAAJgAABICZAAAQAGYCAEAAmAkAAAFgJgAABICZAAAQAGYCAEAAmAkAAAFgJgAABIAJAAAEgAkAAASACQAABIAJAAAEgAkAAASACQAABIAJAAAEgAkAAASACQAAAWAmAAAEgJkAABAAZgIAQACYCQAAAWAmAAAEgJkAABAAZgIAQACYCQAAAWACAAABYAIAAAFgAgAAAWACAAABYAIAAAFgAgAAAWACAAABYAIAAAFgAgBAAJgJAAABYCYAAASAmQAAEABmAgBAAJgJAAABYCYAAASAmQAAEABmAgBAAJgA8EMEEAAmAAAQACYAABAAJgAAEAAmAAAQACYAABAAJgAAEAAmAAAQACYAAASAmQAAEABmAgBAANhlB0yg1aTftYZbAAAAAElFTkSuQmCC",
};

export const FAVICON_SVG = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\"><rect width=\"32\" height=\"32\" rx=\"5\" fill=\"#9ece6a\"/><rect x=\"9\" y=\"9\" width=\"14\" height=\"14\" rx=\"1.5\" fill=\"#0c0e10\"/><rect x=\"13\" y=\"13\" width=\"6\" height=\"6\" fill=\"#9ece6a\"/></svg>";
export const MANIFEST = "{\"name\": \"omarchy-pool\", \"short_name\": \"omarchy-pool\", \"icons\": [{\"src\": \"/icon-192.png\", \"sizes\": \"192x192\", \"type\": \"image/png\"}, {\"src\": \"/icon-512.png\", \"sizes\": \"512x512\", \"type\": \"image/png\"}], \"theme_color\": \"#1a1b26\", \"background_color\": \"#1a1b26\", \"display\": \"browser\", \"start_url\": \"/\"}";

function bytes(b64: string): Uint8Array {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

/** The icon a path names, or null. */
export function icon(path: string): Response | null {
  const file: Record<string, [string, string]> = {
    "/favicon.ico": [B64.ico, "image/x-icon"],
    "/favicon.png": [B64.png32, "image/png"],
    "/favicon.svg": [FAVICON_SVG, "image/svg+xml"],
    "/apple-touch-icon.png": [B64.touch, "image/png"],
    "/apple-touch-icon-precomposed.png": [B64.touch, "image/png"],
    "/icon-192.png": [B64.icon192, "image/png"],
    "/icon-512.png": [B64.icon512, "image/png"],
    "/site.webmanifest": [MANIFEST, "application/manifest+json"],
  };
  const f = file[path];
  if (!f) return null;
  const body = path.endsWith(".svg") || path.endsWith(".webmanifest") ? f[0] : bytes(f[0]);
  return new Response(body, { headers: { "content-type": f[1], "cache-control": "public, max-age=86400" } });
}
